# Generated by Django 5.1.1 on 2024-11-21 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='entrenamientoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=15)),
                ('rol', models.CharField(max_length=30)),
                ('fechaIngreso', models.DateField()),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='solicitudEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='claseGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('max_participantes', models.PositiveIntegerField()),
                ('lugar', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('archivar', models.BooleanField(default=False)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_grupales', to='primerApp.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='solicitudCG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('correoElectronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('condicionMedica', models.TextField(blank=True)),
                ('contactoEmergenciaNombre', models.CharField(max_length=100)),
                ('contactoEmergenciaTelefono', models.CharField(max_length=12)),
                ('acepta_reglamento', models.BooleanField(default=False)),
                ('acepta_uso_imagen', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('fechaSolicitud', models.DateTimeField(auto_now_add=True)),
                ('CG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='primerApp.clasegrupal')),
            ],
        ),
        migrations.CreateModel(
            name='integra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('clase_grupal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='primerApp.clasegrupal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='primerApp.cliente')),
                ('solicitud', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primerApp.solicitudcg')),
            ],
        ),
    ]
