# Generated by Django 5.1.1 on 2024-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imgReferencia',
            field=models.ImageField(blank=True, null=True, upload_to='equipo_imgs/'),
        ),
    ]
