# Generated by Django 5.1.1 on 2024-11-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0002_equipo_imgreferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imgReferencia',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/equipo/'),
        ),
    ]
