# Generated by Django 5.1.1 on 2024-11-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0003_alter_equipo_imgreferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasegrupal',
            name='imgReferencia',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/clasesGrupales/'),
        ),
    ]
