# Generated by Django 5.1.1 on 2024-11-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0005_remove_clasegrupal_fecha_clasegrupal_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='pikochu', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
