# Generated by Django 5.1.1 on 2024-11-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0006_producto_descripcion_producto_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='rut',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
