# Generated by Django 5.1.1 on 2024-11-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0007_alter_equipo_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasegrupal',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_grupales', to='primerApp.equipo', to_field='rut'),
        ),
    ]
