# Generated by Django 5.1.1 on 2024-11-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0009_rename_imgreferencia_clasegrupal_imgcg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imgPro',
            field=models.ImageField(upload_to='static/img/productos/'),
        ),
    ]
